In [1]:
import numpy as np

Size = int(input("Input: \n"))

A = np.random.random((Size, Size))

print("\nOutput: ")
print(A)

RowNum, ColNum = A.shape

NewRowNum = RowNum // 2
NewColNum = ColNum // 2

A = A[0:NewRowNum*2, 0:NewColNum*2].reshape(NewRowNum, 2, NewColNum, 2).max(axis=(1, 3))

print(A)


Input: 
4

Output: 
[[0.83188884 0.50496294 0.20485422 0.69936774]
 [0.81214546 0.38975543 0.51879002 0.77652964]
 [0.92015747 0.73063527 0.46316099 0.2341451 ]
 [0.85624807 0.1197388  0.57820452 0.49010029]]
[[0.83188884 0.77652964]
 [0.92015747 0.57820452]]
